FROM node:buster-slim as base
WORKDIR /app
ENV PATH $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
RUN apt update && \
    apt install -y git xdg-utils && \
    npm install -g degit && \
    yarn global add vite
EXPOSE 3000
RUN ["/bin/bash"]