FROM mcr.microsoft.com/dotnet/sdk:latest as base
ENV PATH="$PATH:/root/.dotnet/tools"
WORKDIR /app
RUN dotnet tool install --global dotnet-ef
RUN dotnet tool install --global dotnet-aspnet-codegenerator
RUN dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p developmentonly
RUN dotnet dev-certs https --trust
CMD ["/bin/bash"]